import { Item } from './types';

export const sold: Array<Item> = [
  {
    mint: "0",
    data: { name: "Binary Punk #52" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "1",
    data: { name: "Binary Punk #198" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "2",
    data: { name: "Binary Punk #723" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "3",
    data: { name: "Binary Punk #881" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "4",
    data: { name: "Binary Punk #1018" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "5",
    data: { name: "Binary Punk #1386" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "6",
    data: { name: "Binary Punk #1454" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "7",
    data: { name: "Binary Punk #1930" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "8",
    data: { name: "Binary Punk #1949" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "9",
    data: { name: "Binary Punk #1955" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "10",
    data: { name: "Binary Punk #2757" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "11",
    data: { name: "Binary Punk #2937" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "12",
    data: { name: "Binary Punk #3307" },
    type: "rank",
    rank: "12",
    sold: true,
  },
  {
    mint: "12",
    data: { name: "Binary Punk #3307" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "13",
    data: { name: "Binary Punk #3850" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "14",
    data: { name: "Binary Punk #4109" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "15",
    data: { name: "Binary Punk #4234" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "16",
    data: { name: "Binary Punk #4681" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "17",
    data: { name: "Binary Punk #4890" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "18",
    data: { name: "Binary Punk #5053" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "19",
    data: { name: "Binary Punk #5099" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "20",
    data: { name: "Binary Punk #5110" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "22",
    data: { name: "Binary Punk #6357" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "23",
    data: { name: "Binary Punk #6802" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "24",
    data: { name: "Binary Punk #6867" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "25",
    data: { name: "Binary Punk #7018" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "26",
    data: { name: "Binary Punk #7615" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "27",
    data: { name: "Binary Punk #7656" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "28",
    data: { name: "Binary Punk #8557" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "29",
    data: { name: "Binary Punk #8790" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "30",
    data: { name: "Binary Punk #9042" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "31",
    data: { name: "Binary Punk #9339" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "32",
    data: { name: "Binary Punk #9865" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "33",
    data: { name: "Binary Punk #9993" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "46",
    data: { name: "Binary Punk #2891" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "64",
    data: { name: "Binary Punk #6466" },
    type: "rank",
    rank: "12",
    sold: true,
  },
  {
    mint: "103",
    data: { name: "Binary Punk #9203" },
    type: "rank",
    rank: "13",
    sold: true,
  },
  {
    mint: "114",
    data: { name: "Binary Punk #755" },
    type: "rank",
    rank: "27",
    sold: true,
  },
  {
    mint: "114",
    data: { name: "Binary Punk #755" },
    type: "rank",
    rank: "11",
    sold: true,
  },
  {
    mint: "172",
    data: { name: "Binary Punk #1021" },
    type: "rank",
    rank: "48",
    sold: true,
  },
  {
    mint: "192",
    data: { name: "Binary Punk #741" },
    type: "rank",
    rank: "16",
    sold: true,
  },
  {
    mint: "195",
    data: { name: "Binary Punk #4156" },
    type: "rank",
    rank: "46",
    sold: true,
  },
  {
    mint: "198",
    data: { name: "Binary Punk #9280" },
    type: "rank",
    rank: "31",
    sold: true,
  },
  {
    mint: "231",
    data: { name: "Binary Punk #641" },
    type: "rank",
    rank: "14",
    sold: true,
  },
  {
    mint: "231",
    data: { name: "Binary Punk #641" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "260",
    data: { name: "Binary Punk #5577" },
    type: "rank",
    rank: "33",
    sold: true,
  },
  {
    mint: "299",
    data: { name: "Binary Punk #2202" },
    type: "rank",
    rank: "19",
    sold: true,
  },
  {
    mint: "299",
    data: { name: "Binary Punk #2202" },
    type: "rank",
    rank: "3",
    sold: true,
  },
  {
    mint: "413",
    data: { name: "Binary Punk #5949" },
    type: "rank",
    rank: "26",
    sold: true,
  },
  {
    mint: "413",
    data: { name: "Binary Punk #5949" },
    type: "rank",
    rank: "8",
    sold: true,
  },
  {
    mint: "421",
    data: { name: "Binary Punk #5795" },
    type: "rank",
    rank: "36",
    sold: true,
  },
  {
    mint: "427",
    data: { name: "Binary Punk #3871" },
    type: "rank",
    rank: "19",
    sold: true,
  },
  {
    mint: "432",
    data: { name: "Binary Punk #1123" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "536",
    data: { name: "Binary Punk #1050" },
    type: "rank",
    rank: "15",
    sold: true,
  },
  {
    mint: "581",
    data: { name: "Binary Punk #6915" },
    type: "rank",
    rank: "42",
    sold: true,
  },
  {
    mint: "706",
    data: { name: "Binary Punk #2940" },
    type: "rank",
    rank: "31",
    sold: true,
  },
  {
    mint: "781",
    data: { name: "Binary Punk #8498" },
    type: "rank",
    rank: "30",
    sold: true,
  },
  {
    mint: "816",
    data: { name: "Binary Punk #3424" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "850",
    data: { name: "Binary Punk #1653" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "938",
    data: { name: "Binary Punk #7661" },
    type: "rank",
    rank: "32",
    sold: true,
  },
  {
    mint: "1179",
    data: { name: "Binary Punk #1179" },
    type: "match mint",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "1264",
    data: { name: "Binary Punk #3301" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "1297",
    data: { name: "Binary Punk #6795" },
    type: "rank",
    rank: "18",
    sold: true,
  },
  {
    mint: "1361",
    data: { name: "Binary Punk #2240" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "1573",
    data: { name: "Binary Punk #1573" },
    type: "match mint",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "1646",
    data: { name: "Binary Punk #2002" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "1669",
    data: { name: "Binary Punk #1839" },
    type: "rank",
    rank: "28",
    sold: true,
  },
  {
    mint: "1669",
    data: { name: "Binary Punk #1839" },
    type: "rank",
    rank: "16",
    sold: true,
  },
  {
    mint: "1675",
    data: { name: "Binary Punk #428" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "1770",
    data: { name: "Binary Punk #6487" },
    type: "rank",
    rank: "11",
    sold: true,
  },
  {
    mint: "1771",
    data: { name: "Binary Punk #5331" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "1786",
    data: { name: "Binary Punk #9964" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "1815",
    data: { name: "Binary Punk #9804" },
    type: "rank",
    rank: "26",
    sold: true,
  },
  {
    mint: "2007",
    data: { name: "Binary Punk #563" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "2192",
    data: { name: "Binary Punk #8191" },
    type: "rank",
    rank: "30",
    sold: true,
  },
  {
    mint: "2272",
    data: { name: "Binary Punk #5375" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "2373",
    data: { name: "Binary Punk #4874" },
    type: "rank",
    rank: "6",
    sold: true,
  },
  {
    mint: "2772",
    data: { name: "Binary Punk #9163" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "3142",
    data: { name: "Binary Punk #8467" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "3216",
    data: { name: "Binary Punk #5628" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "3318",
    data: { name: "Binary Punk #635" },
    type: "rank",
    rank: "9",
    sold: true,
  },
  {
    mint: "3321",
    data: { name: "Binary Punk #8000" },
    type: "rank",
    rank: "28",
    sold: true,
  },
  {
    mint: "3479",
    data: { name: "Binary Punk #4121" },
    type: "rank",
    rank: "20",
    sold: true,
  },
  {
    mint: "3479",
    data: { name: "Binary Punk #4121" },
    type: "rank",
    rank: "5",
    sold: true,
  },
  {
    mint: "3523",
    data: { name: "Binary Punk #4765" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "3594",
    data: { name: "Binary Punk #372" },
    type: "rank",
    rank: "37",
    sold: true,
  },
  {
    mint: "3603",
    data: { name: "Binary Punk #9957" },
    type: "rank",
    rank: "15",
    sold: true,
  },
  {
    mint: "3622",
    data: { name: "Binary Punk #5008" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "3625",
    data: { name: "Binary Punk #2657" },
    type: "rank",
    rank: "25",
    sold: true,
  },
  {
    mint: "3812",
    data: { name: "Binary Punk #2386" },
    type: "rank",
    rank: "44",
    sold: true,
  },
  {
    mint: "3840",
    data: { name: "Binary Punk #5905" },
    type: "rank",
    rank: "5, 74",
    sold: true,
  },
  {
    mint: "3892",
    data: { name: "Binary Punk #281" },
    type: "rank",
    rank: "18",
    sold: true,
  },
  {
    mint: "3931",
    data: { name: "Binary Punk #3443" },
    type: "rank",
    rank: "4",
    sold: true,
  },
  {
    mint: "3935",
    data: { name: "Binary Punk #9190" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "4042",
    data: { name: "Binary Punk #3575" },
    type: "appearance",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "4043",
    data: { name: "Binary Punk #4957" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "4062",
    data: { name: "Binary Punk #9368" },
    type: "appearance",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "4242",
    data: { name: "Binary Punk #340" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "4296",
    data: { name: "Binary Punk #602" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "4341",
    data: { name: "Binary Punk #909" },
    type: "background",
    rank: "Rank",
    sold: true,
  },
  {
    mint: "4397",
    data: { name: "Binary Punk #2708" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "4411",
    data: { name: "Binary Punk #3398" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "4464",
    data: { name: "Binary Punk #8506" },
    type: "rank",
    rank: "747",
  },
  {
    mint: "4473",
    data: { name: "Binary Punk #5684" },
    type: "rank",
    rank: "57",
  },
  {
    mint: "4499",
    data: { name: "Binary Punk #4485" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "4600",
    data: { name: "Binary Punk #7804" },
    type: "alien",
    rank: "2, 14",
  },
];
