import { Item } from './types';

export const watchlist: Array<Item> = [
  {
    mint: "4489",
    data: { name: "Binary Punk #5721" },
    type: "rank",
    rank: "250",
  },
  {
    mint: "4499",
    data: { name: "Binary Punk #4485" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "4508",
    data: { name: "Binary Punk #8368" },
    type: "appearance",
    rank: "Rank",
  },
  {
    mint: "4600",
    data: { name: "Binary Punk #7804" },
    type: "alien",
    rank: "2, 14",
  },
  {
    mint: "4614",
    data: { name: "Binary Punk #7270" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "4666",
    data: { name: "Binary Punk #4464" },
    type: "ape",
    rank: "32, 34",
  },
  {
    mint: "4751",
    data: { name: "Binary Punk #6832" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "4776",
    data: { name: "Binary Punk #6296" },
    type: "appearance",
    rank: "Rank",
  },
  {
    mint: "4821",
    data: { name: "Binary Punk #5361" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "4835",
    data: { name: "Binary Punk #9057" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "4848",
    data: { name: "Binary Punk #7127" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "4923",
    data: { name: "Binary Punk #4830" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "4957",
    data: { name: "Binary Punk #8870" },
    type: "appearance",
    rank: "Rank",
  },
  {
    mint: "5023",
    data: { name: "Binary Punk #4112" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "5054",
    data: { name: "Binary Punk #1802" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "5062",
    data: { name: "Binary Punk #5893" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "5063",
    data: { name: "Binary Punk #6649" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "5074",
    data: { name: "Binary Punk #9912" },
    type: "rank",
    rank: "35",
  },
  {
    mint: "5085",
    data: { name: "Binary Punk #3011" },
    type: "rank",
    rank: "23, 7",
  },
  {
    mint: "5146",
    data: { name: "Binary Punk #57" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "5261",
    data: { name: "Binary Punk #7971" },
    type: "rank",
    rank: "29, 20",
  },
  {
    mint: "5288",
    data: { name: "Binary Punk #4206" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "5297",
    data: { name: "Binary Punk #745" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "5303",
    data: { name: "Binary Punk #2033" },
    type: "rank",
    rank: "24",
  },
  {
    mint: "5356",
    data: { name: "Binary Punk #5203" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "5399",
    data: { name: "Binary Punk #117" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "5434",
    data: { name: "Binary Punk #510" },
    type: "rank",
    rank: "17",
  },
  {
    mint: "5451",
    data: { name: "Binary Punk #4699" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "5536",
    data: { name: "Binary Punk #1576" },
    type: "hostage",
    rank: "Rank",
  },
  {
    mint: "5593",
    data: { name: "Binary Punk #5622" },
    type: "rank",
    rank: "22, 4",
  },
  {
    mint: "5619",
    data: { name: "Binary Punk #7671" },
    type: "rank",
    rank: "22",
  },
  {
    mint: "5626",
    data: { name: "Binary Punk #156" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "5673",
    data: { name: "Binary Punk #4178" },
    type: "ape",
    rank: "39",
  },
  {
    mint: "5786",
    data: { name: "Binary Punk #5822" },
    type: "alien",
    rank: "8",
  },
  {
    mint: "5835",
    data: { name: "Binary Punk #7735" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "5891",
    data: { name: "Binary Punk #8472" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "5910",
    data: { name: "Binary Punk #7468" },
    type: "appearance",
    rank: "Rank",
  },
  {
    mint: "5935",
    data: { name: "Binary Punk #7523" },
    type: "alien",
    rank: "3, 23",
  },
  {
    mint: "5960",
    data: { name: "Binary Punk #2560" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "5979",
    data: { name: "Binary Punk #3100" },
    type: "alien",
    rank: "7",
  },
  {
    mint: "6077",
    data: { name: "Binary Punk #4535" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "6084",
    data: { name: "Binary Punk #2460" },
    type: "ape",
    rank: "45",
  },
  {
    mint: "6097",
    data: { name: "Binary Punk #4008" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "6126",
    data: { name: "Binary Punk #3393" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "6144",
    data: { name: "Binary Punk #3609" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "6172",
    data: { name: "Binary Punk #6153" },
    type: "rank",
    rank: "25, 10",
  },
  {
    mint: "6175",
    data: { name: "Binary Punk #9967" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "6264",
    data: { name: "Binary Punk #2924" },
    type: "ape",
    rank: "38",
  },
  {
    mint: "6399",
    data: { name: "Binary Punk #8400" },
    type: "appearance",
    rank: "Rank",
  },
  {
    mint: "6405",
    data: { name: "Binary Punk #8344" },
    type: "appearance",
    rank: "Rank",
  },
  {
    mint: "6455",
    data: { name: "Binary Punk #3809" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "6475",
    data: { name: "Binary Punk #6117" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "6485",
    data: { name: "Binary Punk #6943" },
    type: "rank",
    rank: "29",
  },
  {
    mint: "6518",
    data: { name: "Binary Punk #7756" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "6538",
    data: { name: "Binary Punk #965" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "6647",
    data: { name: "Binary Punk #4513" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "6825",
    data: { name: "Binary Punk #2204" },
    type: "rank",
    rank: "13",
  },
  {
    mint: "6866",
    data: { name: "Binary Punk #9474" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "6872",
    data: { name: "Binary Punk #3069" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "6892",
    data: { name: "Binary Punk #9943" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "6895",
    data: { name: "Binary Punk #5071" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "6970",
    data: { name: "Binary Punk #5573" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "6987",
    data: { name: "Binary Punk #2711" },
    type: "ape",
    rank: "Rank",
  },
  {
    mint: "7014",
    data: { name: "Binary Punk #7602" },
    type: "rank",
    rank: "17",
  },
  {
    mint: "7017",
    data: { name: "Binary Punk #1886" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "7040",
    data: { name: "Binary Punk #3014" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "7050",
    data: { name: "Binary Punk #9038" },
    type: "rank",
    rank: "27",
  },
  {
    mint: "7074",
    data: { name: "Binary Punk #2132" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "7135",
    data: { name: "Binary Punk #1351" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "7142",
    data: { name: "Binary Punk #5066" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "7171",
    data: { name: "Binary Punk #9909" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "7211",
    data: { name: "Binary Punk #7132" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "7237",
    data: { name: "Binary Punk #5234" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "7240",
    data: { name: "Binary Punk #2213" },
    type: "appearance",
    rank: "Rank",
  },
  {
    mint: "7366",
    data: { name: "Binary Punk #5489" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "7434",
    data: { name: "Binary Punk #802" },
    type: "hostage",
    rank: "Rank",
  },
  {
    mint: "7458",
    data: { name: "Binary Punk #6087" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "7471",
    data: { name: "Binary Punk #8307" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "7497",
    data: { name: "Binary Punk #5025" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "7597",
    data: { name: "Binary Punk #7519" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "7607",
    data: { name: "Binary Punk #1119" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "7642",
    data: { name: "Binary Punk #6965" },
    type: "ape",
    rank: "35",
  },
  {
    mint: "7651",
    data: { name: "Binary Punk #5687" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "7720",
    data: { name: "Binary Punk #6784" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "7748",
    data: { name: "Binary Punk #5374" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "7796",
    data: { name: "Binary Punk #8348" },
    type: "rank",
    rank: "1",
  },
  {
    mint: "7821",
    data: { name: "Binary Punk #2938" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "7841",
    data: { name: "Binary Punk #2140" },
    type: "ape",
    rank: "47",
  },
  {
    mint: "7864",
    data: { name: "Binary Punk #8219" },
    type: "ape",
    rank: "41",
  },
  {
    mint: "7950",
    data: { name: "Binary Punk #5217" },
    type: "ape",
    rank: "34",
  },
  {
    mint: "8014",
    data: { name: "Binary Punk #2491" },
    type: "ape",
    rank: "40",
  },
  {
    mint: "8022",
    data: { name: "Binary Punk #5336" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "8071",
    data: { name: "Binary Punk #8126" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "8086",
    data: { name: "Binary Punk #4338" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "8102",
    data: { name: "Binary Punk #2424" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "8136",
    data: { name: "Binary Punk #4783" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "8195",
    data: { name: "Binary Punk #1190" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "8223",
    data: { name: "Binary Punk #2329" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "8226",
    data: { name: "Binary Punk #5412" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "8284",
    data: { name: "Binary Punk #2890" },
    type: "alien",
    rank: "6",
  },
  {
    mint: "8387",
    data: { name: "Binary Punk #8050" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "8392",
    data: { name: "Binary Punk #6304" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "8405",
    data: { name: "Binary Punk #1658" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "8433",
    data: { name: "Binary Punk #1078" },
    type: "hostage",
    rank: "Rank",
  },
  {
    mint: "8463",
    data: { name: "Binary Punk #8769" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "8474",
    data: { name: "Binary Punk #4301" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "8511",
    data: { name: "Binary Punk #6491" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "8541",
    data: { name: "Binary Punk #6470" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "8697",
    data: { name: "Binary Punk #2681" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "8726",
    data: { name: "Binary Punk #264" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "8759",
    data: { name: "Binary Punk #6049" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "8807",
    data: { name: "Binary Punk #6089" },
    type: "alien",
    rank: "10",
  },
  {
    mint: "8837",
    data: { name: "Binary Punk #7453" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "8925",
    data: { name: "Binary Punk #8531" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "8943",
    data: { name: "Binary Punk #6215" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "9012",
    data: { name: "Binary Punk #8896" },
    type: "appearance",
    rank: "Rank",
  },
  {
    mint: "9055",
    data: { name: "Binary Punk #2106" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "9057",
    data: { name: "Binary Punk #8152" },
    type: "rank",
    rank: "24, 9",
  },
  {
    mint: "9092",
    data: { name: "Binary Punk #5314" },
    type: "ape",
    rank: "43",
  },
  {
    mint: "9128",
    data: { name: "Binary Punk #7458" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "9150",
    data: { name: "Binary Punk #8780" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "9185",
    data: { name: "Binary Punk #7920" },
    type: "rank",
    rank: "21, 2",
  },
  {
    mint: "9194",
    data: { name: "Binary Punk #4415" },
    type: "rank",
    rank: "33",
  },
  {
    mint: "9279",
    data: { name: "Binary Punk #1034" },
    type: "hostage",
    rank: "Rank",
  },
  {
    mint: "9281",
    data: { name: "Binary Punk #3028" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "9312",
    data: { name: "Binary Punk #5346" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "9335",
    data: { name: "Binary Punk #3452" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "9367",
    data: { name: "Binary Punk #5944" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "9402",
    data: { name: "Binary Punk #8553" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "9470",
    data: { name: "Binary Punk #7604" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "9493",
    data: { name: "Binary Punk #5775" },
    type: "appearance",
    rank: "Rank",
  },
  {
    mint: "9494",
    data: { name: "Binary Punk #2338" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "9523",
    data: { name: "Binary Punk #6704" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "9597",
    data: { name: "Binary Punk #3328" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "9646",
    data: { name: "Binary Punk #1435" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "9664",
    data: { name: "Binary Punk #1374" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "9709",
    data: { name: "Binary Punk #7757" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "9760",
    data: { name: "Binary Punk #6297" },
    type: "zombie",
    rank: "Rank",
  },
  {
    mint: "9897",
    data: { name: "Binary Punk #9998" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "9980",
    data: { name: "Binary Punk #8169" },
    type: "background",
    rank: "Rank",
  },
  {
    mint: "9997",
    data: { name: "Binary Punk #7956" },
    type: "rank",
    rank: "21",
  },
];
